#!/bin/bash

style="--style=kr --indent=spaces=4 --indent-namespaces --lineend=linux --min-conditional-indent=0"
options="--options=none --pad-header --unpad-paren --suffix=none --convert-tabs --attach-inlines --attach-classes --attach-namespaces"

astyle $style $options *.cpp
astyle $style $options *.h
astyle $style $options test/*.cpp
